// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-YycV1i6c71l3P-Q4d51xqr4cl7iunzk',
    appId: '1:418435556200:web:c14550cb7775baa8d52cdd',
    messagingSenderId: '418435556200',
    projectId: 'mae-assignment-16065',
    authDomain: 'mae-assignment-16065.firebaseapp.com',
    storageBucket: 'mae-assignment-16065.firebasestorage.app',
    measurementId: 'G-GN32TDEVTL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfNr6OMRoCu53tcWwrYruy5pDkjc1KdFs',
    appId: '1:418435556200:android:8514ed8b17576ee5d52cdd',
    messagingSenderId: '418435556200',
    projectId: 'mae-assignment-16065',
    storageBucket: 'mae-assignment-16065.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG8OfJfhWqlC0gO1skuy79QFoMfVnM4y0',
    appId: '1:418435556200:ios:742f98c65c2701d9d52cdd',
    messagingSenderId: '418435556200',
    projectId: 'mae-assignment-16065',
    storageBucket: 'mae-assignment-16065.firebasestorage.app',
    iosBundleId: 'com.example.moneymate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG8OfJfhWqlC0gO1skuy79QFoMfVnM4y0',
    appId: '1:418435556200:ios:742f98c65c2701d9d52cdd',
    messagingSenderId: '418435556200',
    projectId: 'mae-assignment-16065',
    storageBucket: 'mae-assignment-16065.firebasestorage.app',
    iosBundleId: 'com.example.moneymate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-YycV1i6c71l3P-Q4d51xqr4cl7iunzk',
    appId: '1:418435556200:web:8d2be8c267daef48d52cdd',
    messagingSenderId: '418435556200',
    projectId: 'mae-assignment-16065',
    authDomain: 'mae-assignment-16065.firebaseapp.com',
    storageBucket: 'mae-assignment-16065.firebasestorage.app',
    measurementId: 'G-1X1P3EVF00',
  );
}
